USE [master]
GO

/****** Object:  Database [DVD]    Script Date: 4/7/2016 5:10:22 PM ******/
CREATE DATABASE [DVD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DVD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQL2014\MSSQL\DATA\DVD.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DVD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQL2014\MSSQL\DATA\DVD_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DVD] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DVD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DVD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DVD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DVD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DVD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DVD] SET ARITHABORT OFF 
GO

ALTER DATABASE [DVD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DVD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DVD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DVD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DVD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DVD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DVD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DVD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DVD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DVD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DVD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DVD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DVD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DVD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DVD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DVD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DVD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DVD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DVD] SET  MULTI_USER 
GO

ALTER DATABASE [DVD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DVD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DVD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DVD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DVD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DVD] SET  READ_WRITE 
GO

